"""산출물: JSON/CSV 내보내기 + 자체 포함 단일 HTML 뷰어 생성."""
from __future__ import annotations

import csv
import html as htmllib
import json
from pathlib import Path

from .store import Store

VIEWER_TEMPLATE = """<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<title>{title} 아카이브</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root {{ --line:#d8d8d8; --ink:#1b1b1b; --muted:#6a6a6a; --bg:#fbfaf8; }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; background:var(--bg); color:var(--ink);
         font:14px/1.6 -apple-system,"Segoe UI","Malgun Gothic",sans-serif; }}
  header {{ padding:22px 20px 14px; border-bottom:1px solid var(--line); background:#fff; }}
  h1 {{ margin:0 0 4px; font-size:19px; letter-spacing:-.2px; }}
  .sub {{ color:var(--muted); font-size:12.5px; }}
  .bar {{ display:flex; gap:10px; flex-wrap:wrap; align-items:center;
          padding:12px 20px; border-bottom:1px solid var(--line); background:#fff;
          position:sticky; top:0; z-index:5; }}
  input[type=search], select {{ padding:7px 9px; border:1px solid var(--line); background:#fff;
          font:inherit; font-size:13px; color:var(--ink); }}
  input[type=search] {{ width:280px; }}
  .count {{ color:var(--muted); font-size:12.5px; margin-left:auto; }}
  main {{ padding:0 20px 60px; }}
  table {{ width:100%; border-collapse:collapse; background:#fff; }}
  th, td {{ text-align:left; padding:9px 8px; border-bottom:1px solid #ececec; vertical-align:top; }}
  th {{ font-size:12px; color:var(--muted); font-weight:600; background:#fff; position:sticky; top:53px; }}
  tr.row {{ cursor:pointer; }}
  tr.row:hover {{ background:#f6f5f2; }}
  .num {{ color:var(--muted); font-variant-numeric:tabular-nums; width:70px; }}
  .date {{ color:var(--muted); white-space:nowrap; width:105px; }}
  .who {{ color:var(--muted); width:90px; }}
  .views {{ color:var(--muted); width:60px; text-align:right; }}
  .att {{ width:52px; color:#8a1f11; font-size:12px; }}
  .tag {{ display:inline-block; font-size:11px; color:#6b4a00; background:#fdf3d8;
          border:1px solid #efe0b0; padding:0 5px; margin-right:6px; }}
  .body {{ background:#fdfdfc; }}
  .body pre {{ white-space:pre-wrap; word-break:break-word; margin:6px 0 2px;
               font:13px/1.65 "Malgun Gothic","Segoe UI",sans-serif; }}
  .files a {{ display:inline-block; margin:3px 10px 0 0; font-size:12.5px; color:#1a4f8a; }}
  .hidden {{ display:none; }}
  footer {{ padding:14px 20px; color:var(--muted); font-size:12px; border-top:1px solid var(--line); }}
</style>
</head>
<body>
<header>
  <h1>{title} 게시판 아카이브</h1>
  <div class="sub">{base_url} · 수집 {generated} · 게시글 {n_posts}건 · 첨부 {n_att}건
    · <a href="posts.json">posts.json</a> · <a href="attachments.csv">attachments.csv</a>
    · <a href="summary.json">summary.json</a></div>
</header>
<div class="bar">
  <input type="search" id="q" placeholder="제목·본문·작성자 검색">
  <select id="board"><option value="">전체 게시판</option>{board_options}</select>
  <label class="sub"><input type="checkbox" id="onlyatt"> 첨부만</label>
  <span class="count" id="count"></span>
</div>
<main>
<table>
  <thead><tr><th class="num">번호</th><th>제목</th><th class="who">작성자</th>
  <th class="date">작성일</th><th class="views">조회</th><th class="att">첨부</th></tr></thead>
  <tbody id="tb"></tbody>
</table>
</main>
<footer>generated by dkis-archive · 데이터 출처: {base_url}</footer>
<script id="data" type="application/json">{data_json}</script>
<script>
const POSTS = JSON.parse(document.getElementById('data').textContent);
const ATTS  = {atts_json};
const tb = document.getElementById('tb'), q = document.getElementById('q'),
      bd = document.getElementById('board'), oa = document.getElementById('onlyatt'),
      cnt = document.getElementById('count');
function esc(s){{return (s||'').replace(/[&<>"]/g, c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}})[c]);}}
function render() {{
  const kw = q.value.trim().toLowerCase(), b = bd.value, only = oa.checked;
  const list = POSTS.filter(p =>
      (!b || String(p.menu_no) === b) &&
      (!only || (ATTS[p.key]||[]).length) &&
      (!kw || (p.title+' '+p.author+' '+(p.text||'')).toLowerCase().includes(kw)));
  cnt.textContent = list.length + ' / ' + POSTS.length + '건';
  tb.innerHTML = list.slice(0, 2000).map(p => {{
    const files = (ATTS[p.key]||[]).map(a =>
      `<a href="${{esc(a.local||a.url)}}" target="_blank">${{esc(a.filename)}}</a>`).join(' ');
    return `<tr class="row" data-k="${{p.key}}">
      <td class="num">${{p.bno}}</td>
      <td>${{p.notice?'<span class="tag">공지</span>':''}}${{esc(p.title)}}</td>
      <td class="who">${{esc(p.author)}}</td>
      <td class="date">${{esc(p.posted_at||'')}}</td>
      <td class="views">${{p.views??''}}</td>
      <td class="att">${{(ATTS[p.key]||[]).length ? (ATTS[p.key][0].ext||'파일') : ''}}</td></tr>
    <tr class="body hidden" data-body="${{p.key}}"><td colspan="6">
      <pre>${{esc(p.text||'(본문 없음)')}}</pre>
      <div class="files">${{files}}</div>
    </td></tr>`;
  }}).join('');
}}
tb.addEventListener('click', e => {{
  const tr = e.target.closest('tr.row'); if (!tr) return;
  const body = tb.querySelector(`tr.body[data-body="${{tr.dataset.k}}"]`);
  if (body) body.classList.toggle('hidden');
}});
[q, bd, oa].forEach(el => el.addEventListener('input', render));
render();
</script>
</body>
</html>
"""


def export_json(store: Store, site: dict, out_dir: str | Path, *, text_limit: int = 4000) -> dict:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    posts = []
    for r in store.iter_posts(site["key"]):
        posts.append({
            "key": f'{r["menu_no"]}:{r["bno"]}',
            "menu_no": r["menu_no"],
            "board": site["boards"].get(r["menu_no"], {}).get("name", str(r["menu_no"])),
            "bno": r["bno"],
            "title": r["title"],
            "author": r["author"],
            "posted_at": r["posted_at"],
            "posted_date": r["posted_date"],
            "views": r["views"],
            "notice": bool(r["is_notice"]),
            "has_attachment": bool(r["has_attachment"]),
            "url": site["base_url"] + (r["url"] or ""),
            "text": (r["content_text"] or "")[:text_limit],
            "images": json.loads(r["images_json"] or "[]"),
        })
    atts = {}
    rows = store.conn.execute(
        "SELECT menu_no,bno,filename,url,ext,size_bytes,sha256,local_path,status "
        "FROM attachments WHERE site_key=? ORDER BY menu_no,bno", (site["key"],)).fetchall()
    for a in rows:
        atts.setdefault(f'{a["menu_no"]}:{a["bno"]}', []).append({
            "filename": a["filename"], "url": site["base_url"] + (a["url"] or ""),
            "ext": a["ext"], "size_bytes": a["size_bytes"], "sha256": a["sha256"],
            "local": a["local_path"] or "", "status": a["status"],
        })

    (out / "posts.json").write_text(json.dumps(posts, ensure_ascii=False, indent=1), encoding="utf-8")
    (out / "attachments.json").write_text(json.dumps(atts, ensure_ascii=False, indent=1), encoding="utf-8")
    with (out / "attachments.csv").open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(["menu_no", "board", "bno", "filename", "ext", "size_bytes", "sha256", "status", "url"])
        for a in rows:
            w.writerow([a["menu_no"], site["boards"].get(a["menu_no"], {}).get("name", ""),
                        a["bno"], a["filename"], a["ext"], a["size_bytes"], a["sha256"],
                        a["status"], site["base_url"] + (a["url"] or "")])
    with (out / "posts.csv").open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(["menu_no", "board", "bno", "title", "author", "posted_date", "views", "notice",
                    "has_attachment", "url"])
        for p in posts:
            w.writerow([p["menu_no"], p["board"], p["bno"], p["title"], p["author"],
                        p["posted_date"], p["views"], int(p["notice"]), int(p["has_attachment"]), p["url"]])

    summary = store.stats(site["key"])
    summary["site"] = {k: site[k] for k in ("key", "name", "base_url", "school_code") if k in site}
    summary["exported_posts"] = len(posts)
    summary["exported_attachments"] = sum(len(v) for v in atts.values())
    (out / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=1), encoding="utf-8")
    return {"posts": len(posts), "attachments": sum(len(v) for v in atts.values()), "out": str(out)}


def build_viewer(store: Store, site: dict, out_dir: str | Path, *, generated: str = "") -> str:
    """자체 포함 단일 HTML 뷰어 생성 (외부 리소스 없음)."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    posts, atts = [], {}
    for r in store.iter_posts(site["key"]):
        posts.append({
            "key": f'{r["menu_no"]}:{r["bno"]}', "menu_no": r["menu_no"], "bno": r["bno"],
            "title": r["title"] or "", "author": r["author"] or "",
            "posted_at": r["posted_at"] or r["posted_date"] or "", "views": r["views"],
            "notice": bool(r["is_notice"]), "text": (r["content_text"] or "")[:4000],
        })
    for a in store.conn.execute(
            "SELECT menu_no,bno,filename,url,ext,local_path FROM attachments WHERE site_key=? "
            "ORDER BY menu_no,bno", (site["key"],)).fetchall():
        atts.setdefault(f'{a["menu_no"]}:{a["bno"]}', []).append(
            {"filename": a["filename"], "url": site["base_url"] + (a["url"] or ""),
             "ext": a["ext"], "local": a["local_path"] or ""})
    board_options = "".join(
        f'<option value="{m}">{htmllib.escape(site["boards"][m]["name"])}</option>'
        for m in sorted(site["boards"]) if any(p["menu_no"] == m for p in posts))
    html = VIEWER_TEMPLATE.format(
        title=htmllib.escape(site["name"]), base_url=site["base_url"], generated=generated,
        n_posts=len(posts), n_att=sum(len(v) for v in atts.values()),
        board_options=board_options,
        data_json=json.dumps(posts, ensure_ascii=False).replace("</", "<\\/"),
        atts_json=json.dumps(atts, ensure_ascii=False).replace("</", "<\\/"),
    )
    target = out / "index.html"
    target.write_text(html, encoding="utf-8")
    return str(target)
